### ISSUE TITLE
Long time for validation process on Azure Search:

### ISSUE THREAD

**Issue by CodeSizzler** [Azure/LearnAI-KnowledgeMiningBootcamp#12]
Hi,

Am working on ingesting the dataset for Azure Search from Azure Blob Storage, once when I configure the cognitive search to import the data it takes a long time for validation. Am hanged up on the same validating status for more than an hour. Would really appreciate if you could add more lights on the same. 

Source - https://github.com/Azure/LearnAI-KnowledgeMiningBootcamp/blob/master/labs/lab-azure-search.md 

Best,
Code$izzler Team.

**Comment by givenscj** [comment]
This can be caused by not having the storage account in the same region as your Search and Cog services.
