### ISSUE TITLE
Deployment of bot is unclear due to documentation updates

### ISSUE THREAD

**Issue by iMicknl** [Azure/LearnAI-KnowledgeMiningBootcamp#14]
.bot file deployment is deprecated, linked documentation is referring to the new [arm deployment](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=newrg). 

1. Move (partially) away from the .bot approach by 
2. Add the new ARM deployment scripts (https://github.com/microsoft/BotBuilder-Samples/tree/master/generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/DeploymentTemplates)

**Comment by givenscj** [comment]
For the lab testing, the .bot file works for local setup.  But yes, the ARM template is for Azure deployment.
