### ISSUE TITLE
Key Phrase Extraction and Entity Recognition is not working

### ISSUE THREAD

**Issue by isunitha98selvan** [Azure/LearnAI-KnowledgeMiningBootcamp#15]
My blob indexer throws the following warning:
![Screenshot (5)](https://user-images.githubusercontent.com/25410832/59680123-3b9e8800-91ee-11e9-94fe-b1df7910c404.png)

As a result, the languageCode, keyPhrase and Organizations fields in the index are empty.

**Comment by givenscj** [comment]
Hi there, it is likely you may have created/recreated the wrong index structure during one of the steps.  Please verify the index was setup properly to support the indexer and skills.
