### ISSUE TITLE
Please add a highlighting for required ContentModerator Pricing Tier

### ISSUE THREAD

**Issue by th3ragex** [Azure/LearnAI-KnowledgeMiningBootcamp#18]
Please highlight the sentence "We **can't** use the free tier since it only allows 1 TPS (transaction per second)." in "labs/lab-custom-skills.md"

The free tier works at first, but returns inconsistent results. Troubleshooting this is quite frustrating since everything seems to be correct except PII.txt and the other documents are sometimes not flagged for needsModeration as expected.

**Comment by givenscj** [comment]
Hi there, I changed up the formatting a bit in the last update.  It is more clear for anyone doing the labs.  Thanks!
