### ISSUE TITLE
Lab 1 needs to be updated for the recent search updates!

### ISSUE THREAD

**Issue by CRehfuss** [Azure/LearnAI-KnowledgeMiningBootcamp#28]
Some of the naming conventions on the services have changed because of Ignite. So "Azure Search"  should be "Azure Cognitive Search". Also in step 3 it's blobs now instead of containers!

**Comment by Rodrigossz** [comment]
Will work on these issues. Tks

**Comment by Rodrigossz** [comment]
## IMPORTANT MESSAGE - CONTENT RETIREMENT NOTICE

The LearnAI team appreciates your visit, but this training was retired in 2019 and no further maintenance will be done. The team no longer exists and there is no creation of new content. You can use this material as is, no issues or PRs will be considered.

To learn more about AI and Knowledge Mining, check this resources:

+ Microsoft AI School - http://aka.ms/ai-school
+ Azure Cognigite Search - Knowledge Mining Solution Accelerator - http://aka.ms/kmsolutions
+ Azure Cognigite Search - Knowledge Mining Workshop - http://aka.ms/kmw1
+ Microsoft AI Customer Engineering Team Blog - http://aka.ms/ACE-Blog

Thank you for the visit!
