### ISSUE TITLE
Routing Problem

### ISSUE THREAD

**Issue by rajat28negi** [Azure/LearnAI-KnowledgeMiningBootcamp#29]
Since the bot emulator calls for **http://localhost:3978/api/messages** and there is no routing defined in Program. Every time it get hitting the Middleware's OnTurnAsync() and then the CognitiveSearchBot's OnTurnAsync() method . There is no routing controller in the Program not even the adapter class is injected. 
Please explain how its work flow.

**Comment by Rodrigossz** [comment]
## IMPORTANT MESSAGE - CONTENT RETIREMENT NOTICE

The LearnAI team appreciates your visit, but this training was retired in 2019 and no further maintenance will be done. The team no longer exists and there is no creation of new content. You can use this material as is, no issues or PRs will be considered.

To learn more about AI and Knowledge Mining, check this resources:

+ Microsoft AI School - http://aka.ms/ai-school
+ Azure Cognigite Search - Knowledge Mining Solution Accelerator - http://aka.ms/kmsolutions
+ Azure Cognigite Search - Knowledge Mining Workshop - http://aka.ms/kmw1
+ Microsoft AI Customer Engineering Team Blog - http://aka.ms/ACE-Blog

Thank you for the visit!
