### ISSUE TITLE
Lab 2: Step 3: Documents are not getting imported to the Indexer

### ISSUE THREAD

**Issue by SeeratArora** [Azure/LearnAI-KnowledgeMiningBootcamp#30]
[Lab 2: Step 3:](https://github.com/Azure/LearnAI-KnowledgeMiningBootcamp/blob/master/labs/lab-02-azure-cognitive-search.md#step-3---check-indexer-execution-status) The documents are not getting imported to the Indexer. When tried it's showing up as the image shown below:

![image](https://user-images.githubusercontent.com/50323628/82352273-5e977480-9a1b-11ea-9b7f-15bce6961e50.png)

Can you please a take look into this?

Thanks,
Seerat

**Comment by SeeratArora** [comment]
Do we have updates on this?

**Comment by Rodrigossz** [comment]
## IMPORTANT MESSAGE - CONTENT RETIREMENT NOTICE

The LearnAI team appreciates your visit, but this training was retired in 2019 and no further maintenance will be done. The team no longer exists and there is no creation of new content. You can use this material as is, no issues or PRs will be considered.

To learn more about AI and Knowledge Mining, check this resources:

+ Microsoft AI School - http://aka.ms/ai-school
+ Azure Cognigite Search - Knowledge Mining Solution Accelerator - http://aka.ms/kmsolutions
+ Azure Cognigite Search - Knowledge Mining Workshop - http://aka.ms/kmw1
+ Microsoft AI Customer Engineering Team Blog - http://aka.ms/ACE-Blog

Thank you for the visit!
