### ISSUE TITLE
Link to Labs2 is broken in alternate agenda page

### ISSUE THREAD

**Issue by farishaddad** [Azure/LearnAI-KnowledgeMiningBootcamp#5]
The LAB2 link is 404 on https://github.com/Azure/LearnAI-KnowledgeMiningBootcamp/blob/master/resources/md-files/alternative-agendas.md

**Comment by hastagAB** [comment]
I would like to work on it. @farishaddad :100:

**Comment by Rodrigossz** [comment]
TKS!!
