### ISSUE TITLE
lab-text-skills.md demoskillset code has a bug

### ISSUE THREAD

**Issue by christinaleo-msft** [Azure/LearnAI-KnowledgeMiningBootcamp#6]
**Step 2 - Create a Skillset
Skillset Request Body Syntax**

I had to omit this portion of the code that creates the demoskillset in order to get it to work:

"cognitiveServices": {
        "@odata.type": "#Microsoft.Azure.Search.CognitiveServicesByKey",
        "description": "my-cog-serv",
        "key": "your-api-key-here"
  }

**Comment by Rodrigossz** [comment]
Hi! What is the error message? It is critical to work with 20+ documents. And this is the correct syntax. It has been working since it was added. Any help is welcome. TKS

**Comment by givenscj** [comment]
Hi there, we just updated the labs.  As long as you are calling the correct api version you should have no problems.
